export const customDarkStyle = {
    'code[class*="language-"]': {
      color: '#abb2bf',
      background: '#282c34',
      fontFamily: 'Consolas, Monaco, "Andale Mono", "Ubuntu Mono", monospace',
      fontSize: '14px',
      lineHeight: '1.5',
      direction: 'ltr',
      textAlign: 'left',
      whiteSpace: 'pre',
      wordSpacing: 'normal',
      wordBreak: 'normal',
      wordWrap: 'normal',
      tabSize: 4,
      hyphens: 'none'
    },
    'pre[class*="language-"]': {
      color: '#abb2bf',
      background: '#282c34',
      fontFamily: 'Consolas, Monaco, "Andale Mono", "Ubuntu Mono", monospace',
      fontSize: '14px',
      lineHeight: '1.5',
      direction: 'ltr',
      textAlign: 'left',
      whiteSpace: 'pre',
      wordSpacing: 'normal',
      wordBreak: 'normal',
      wordWrap: 'normal',
      tabSize: 4,
      hyphens: 'none',
      padding: '1em',
      margin: '0.5em 0',
      overflow: 'auto'
    },
    comment: { color: '#5c6370', fontStyle: 'italic' },
    prolog: { color: '#5c6370', fontStyle: 'italic' },
    doctype: { color: '#5c6370', fontStyle: 'italic' },
    cdata: { color: '#5c6370', fontStyle: 'italic' },
    punctuation: { color: '#abb2bf' },
    '.namespace': { opacity: 0.7 },
    property: { color: '#d19a66' },
    tag: { color: '#e06c75' },
    boolean: { color: '#d19a66' },
    number: { color: '#d19a66' },
    constant: { color: '#d19a66' },
    symbol: { color: '#d19a66' },
    deleted: { color: '#e06c75' },
    selector: { color: '#98c379' },
    'attr-name': { color: '#d19a66' },
    string: { color: '#98c379' },
    char: { color: '#98c379' },
    builtin: { color: '#e6c07b' },
    inserted: { color: '#98c379' },
    variable: { color: '#e06c75' },
    operator: { color: '#56b6c2' },
    entity: { color: '#56b6c2', cursor: 'help' },
    url: { color: '#56b6c2' },
    '.language-css .token.string': { color: '#56b6c2' },
    '.style .token.string': { color: '#56b6c2' },
    atrule: { color: '#c678dd' },
    'attr-value': { color: '#98c379' },
    keyword: { color: '#c678dd' },
    function: { color: '#61afef' },
    'class-name': { color: '#e6c07b' },
    regex: { color: '#98c379' },
    important: { color: '#c678dd', fontWeight: 'bold' },
    bold: { fontWeight: 'bold' },
    italic: { fontStyle: 'italic' }
  };