import {
  Book,
  GitBranch,
  Eye,
  Star,
  GitFork,
  GitCommit,
  Code,
  AlertCircle,
  GitPullRequest,
  Play,
  Columns,
  Shield,
  GitGraph as Graph,
  Settings,
  ChevronDown,
  RefreshCw,
  File as FileIcon,
  Folder,
  History,
  Pencil,
  Trash2,
  Download,
  BookOpen,
  Calendar,
  FileInput,
  CheckCircle2,
  Plus,
} from 'lucide-react';

export const Icons = {
  book: Book,
  gitBranch: GitBranch,
  gitCommit: GitCommit,
  eye: Eye,
  star: Star,
  gitFork: GitFork,
  code: Code,
  alertCircle: AlertCircle,
  gitPullRequest: GitPullRequest,
  play: Play,
  columns: Columns,
  shield: Shield,
  graph: Graph,
  settings: Settings,
  chevronDown: ChevronDown,
  refresh: RefreshCw,
  file: FileIcon,
  folder: Folder,
  history: History,
  pencil: Pencil,
  trash: Trash2,
  download: Download,
  bookOpen: BookOpen,
  calendar: Calendar,
  raw: FileInput,
  checkCircle: CheckCircle2,
  plus: Plus,
};