import {
  Book,
  GitBranch,
  Eye,
  Star,
  GitFork,
  GitCommit,
  Code,
  AlertCircle,
  GitPullRequest,
  Play,
  Columns,
  Shield,
  GitGraph as Graph,
  Settings,
  ChevronDown,
  RefreshCw,
  File as FileIcon,
  Folder,
  History,
  Pencil,
  Trash2,
  Download,
  BookOpen,
  Calendar,
  FileInput,
  CheckCircle2,
  Plus,
  FileText,
  CircleDot,
  Table,
  BarChart3,
  RefreshCw as RefreshCwIcon,
  Edit,
  ChevronDown as ChevronDownIcon,
  Folder as FolderIcon,
  ChevronRight,
  Globe,
  ChevronLeft,
  Copy,
  Info,
  MoreVertical,
  Terminal,
  Blocks,
  RotateCw,
  Share2,
  Type,
  File,
  Loader,
  Save
} from 'lucide-react';

export const Icons = {
  book: Book,
  gitBranch: GitBranch,
  gitCommit: GitCommit,
  eye: Eye,
  star: Star,
  gitFork: GitFork,
  code: Code,
  alertCircle: AlertCircle,
  gitPullRequest: GitPullRequest,
  play: Play,
  columns: Columns,
  shield: Shield,
  graph: Graph,
  settings: Settings,
  chevronDown: ChevronDown,
  refresh: RefreshCw,
  file: FileIcon,
  folder: Folder,
  history: History,
  pencil: Pencil,
  trash: Trash2,
  download: Download,
  bookOpen: BookOpen,
  calendar: Calendar,
  raw: FileInput,
  checkCircle: CheckCircle2,
  plus: Plus,
  // New icons added
  fileText: FileText,
  circleDot: CircleDot,
  table: Table,
  barChart3: BarChart3,
  refreshCw: RefreshCwIcon,
  edit: Edit,
  chevronDownIcon: ChevronDownIcon,
  folderIcon: FolderIcon,
  chevronRight: ChevronRight,
  globe: Globe,
  // Additional icons used in the code
  chevronLeft: ChevronLeft,
  copy: Copy,
  info: Info,
  moreVertical: MoreVertical,
  terminal: Terminal,
  blocks: Blocks,
  rotateCw: RotateCw,
  share: Share2,
  type: Type,
  loader: Loader,
  magicWand: Share2,
  save: Save
};